category_url = "http://localhost:8002/product/category/"
order_url = "http://localhost:8002/checkout/"
product_url = "http://localhost:8002/product/"
registration_url = "http://localhost:8002/register/"
sub_category_url = "http://localhost:8002/product/sub-category/"